# Copyright (c) 2018 CA. All rights reserved.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

version: '3.4'
services:
  gateway-dev:
    hostname: localhost
    image: caapim/gateway:latest
    ports:
    - "5221:8080"
    - "5222:8443"
    - "5223:80"
    volumes:
    - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman
    - ./bundles/helloworld.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/helloworld.bundle
    secrets:
    - source: license
      target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"
      ENV.CONTEXT_VARIABLE_PROPERTY.BackgroundEnvironmentService.color: "blue"

secrets:
  license:
    file: /mnt/c/Users/famaj/Documents/GitHub/demo-gateway/docker/license.xml
